CREATE TABLE IF NOT EXISTS COMPETITORS(
    ID VARCHAR PRIMARY KEY NOT NULL,
    NAME VARCHAR NOT NULL,
    SURNAME VARCHAR NOT NULL,
    YEAROFBIRTH INT NOT NULL,
    CLUB VARCHAR NOT NULL,
    CATEGORY VARCHAR NOT NULL
);